apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cacerts-csi-driver
  namespace: cert-manager

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-cacerts-csi-driver
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["watch", "get", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "get", "list"]
- apiGroups: ["cert-manager.io"]
  resources: ["issuers", "clusterissuers", "certificates"]
  verbs: ["watch", "get", "list"]
- apiGroups: ["cacerts.csi.cert-manager.io"]
  resources: ["*"]
  verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-cacerts-csi-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-cacerts-csi-driver
subjects:
- kind: ServiceAccount
  name: cert-manager-cacerts-csi-driver
  namespace: cert-manager
