apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: main
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: cacerts
      mountPath: /etc/ssl/certs
  volumes:
  - name: cacerts
    csi:
      driver: cacerts.csi.appscode.com
      volumeAttributes:
        # Specify your custom ca certificates here.
        # secrets: ns/s1,ns/s2
        # issuers: ns/i1,ns/i2
        # clusterIssuers: c1,c2
